version: '1'
services:
  mlflow-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:5000
    volumes:
      - medcattrainer_api-media:/app/media-api
      - medcattrainer_api-db:/app/db
    environment:
      - MODEL_STORAGE_PATH=/app/db/medcatmlflow/models/
      - MLFLOW_DB_URI=sqlite:///mlflow.db
      - LOGS_PATH=/app/logs/

volumes:
  medcattrainer_api-media:
    external: True
  medcattrainer_api-db:
    external: True