name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.9', '3.10', '3.11' ]
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Check types
        run: |
          python -m mypy --follow-imports=normal src/app
      - name: Lint
        run: |
          python -m flake8 src/app
      - name: Tests
        run: |
          python -m unittest discover
      - name: Test-run
        run: |
          MEDCATMLFLOW_DB_URI="sqlite:///`pwd`/temp/storage/mlflow.db" MEDCATMLFLOW_MODEL_STORAGE_PATH="`pwd`/temp/storage/" MEDCATMLFLOW_LOGS_PATH="`pwd`/temp/logs/" MEDCATMLFLOW_GUNICORN_WORKERS=1 MEDCATMLFLOW_GUNICORN_TIMEOUT=120 timeout 2m bash src/app/run_app.sh || echo "Successfully timed out"
