name: release-build

on:
  push:
    tags: [ 'v*.*.*' ]


jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: 'production'

      - name: Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      - name: Build
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          docker build -t martratas/medcatmlflow:$IMAGE_TAG -t martratas/medcatmlflow:latest .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        env:
          IMAGE_TAG: ${{ env.RELEASE_VERSION }}
        run: |
          docker push martratas/medcatmlflow:$IMAGE_TAG
          docker push martratas/medcatmlflow:ubuntu-latest
